fixing datetime to handle locale and UTC times
emeraldwalk/vscode-runonsave pull request #90
Opened 2024-08-26 02:07 UTC by EricGentry045

2024-08-26 02:16 UTC, EricGentry045 commented on README.md
> +[Apache](https://github.com/emeraldwalk/vscode-runonsave/blob/master/LICENSE)
This looks like a whitespace change.  I didn't modify this line intentionally.

2024-09-28 00:55 UTC, bmingles commented
@EricGentry045 This looks useful. Would you mind providing some example commands in the PR description that I can use to verify the functionality?

2024-09-28 00:56 UTC, bmingles requested changes
@EricGentry045 This looks useful. Would you mind providing some example commands in the PR description that I can use to verify the functionality?

Also, I just merged some updates. Will need a rebase or merge.

2024-09-28 06:44 UTC, EricGentry045 commented
fixed merge conflict

2024-09-28 06:56 UTC, EricGentry045 commented
Thanks @bmingles.  Here would be a good use case...

`
{
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.java$",
                "cmd": "git add ${file} && git commit -m 'Auto save ${file} at ${datetime}'"
            },
            {
                "match": "\\.cpp$",
                "cmd": "git add ${file} && git commit -m 'Auto save ${file} at ${datetimeUTC}'"
            },
        ]
    }
}
`

2024-09-30 03:37 UTC, bmingles requested changes
There's a few issues I'm seeing here.

1. There are compilation errors due to a typo (should be `toLocaleString()`) and the 2nd arg of String.replace needs to be a string.
    <img width="630" alt="image" src="https://github.com/user-attachments/assets/22778336-1ca6-491f-a641-dd3a226c1cd3">

2. `new Date()` doesn't actually produce a `UTC` format when it's stringified. It's the local time.
3. The naming convention for date tokens should probably be camelCase `dateTime`
4. I don't like how `javascript's` different `toXXX` methods format the locale date and the stringified date differently, so I'd prefer to find a way to format them more consistently, differing only in timezone offset.

I dug into this a bit to figure out how to make things more consistent with the local / UTC formats. Looks like you can use `toLocaleString` but pass a UTC `timeZone` for the UTC version. I'd also recommend introducing a `dateISO` token since that is a common format.

```javascript
const { locale } = new Intl.DateTimeFormat().resolvedOptions();
const now = new Date();

cmdStr = cmdStr.replace(/\${dateTimeISO}/g, now.toISOString());

// locale formats
cmdStr = cmdStr.replace(/\${dateTime}/g, now.toLocaleString(locale));
cmdStr = cmdStr.replace(
  /\${dateTimeUTC}/g,
  now.toLocaleString(locale, { timeZone: 'UTC' }),
);
```

2024-09-30 09:38 UTC, closed without merging